### ISSUE TITLE
Error starting mount.py

### ISSUE THREAD

**Issue by maciak** [jakibaki/switch-usb-mounter#1]
Hi,
When I start mount.py with drive letter on windows 10 with phyton 3.7 installed I only get this:
`Traceback (most recent call last):
  File "C:\Users\macia\Desktop\mount.py", line 8, in <module>
    import handleusb
  File "C:\Users\macia\Desktop\handleusb.py", line 1, in <module>
    import usb.core
ModuleNotFoundError: No module named 'usb'`

**Comment by jakibaki** [comment]
```
To use you need Python3, Fuse (winfsp works on windows, osxfuse on macOS) and pyusb.
```
